name: neo_bank
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2201272

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter_intl:
  enabled: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  domain:
    path: domain
  data:
    path: data

  card_swiper:
    git:
      url: https://github.com/TheAnkurPanchani/card_swiper.git
      ref: master

  flutter_riverpod: 0.14.0+1
  dartz: ^0.10.0
  rxdart: ^0.27.2
  fluttertoast: ^8.0.8
  responsive_builder: ^0.4.1
  animated_theme_switcher: ^2.0.1
  flutter_svg: ^0.22.0
  responsive_framework: ^0.1.4
  intl: 0.17.0
  flutter_svg_provider: ^0.1.10
  dots_indicator: ^2.0.0
  carousel_slider: ^4.0.0
  animated_widgets: ^1.1.0
  pin_code_fields: ^7.3.0
  flutter_countdown_timer: ^4.1.0
  another_transformer_page_view: ^1.0.1
  flutter_switch: ^0.3.2
  show_up_animation: ^2.0.0
  top_snackbar_flutter: ^1.0.1
  google_maps_flutter: ^2.0.9
  fading_edge_scrollview: ^2.0.1
  table_calendar: ^3.0.3
  clickable_list_wheel_view: ^0.0.4
  #  card_swiper: ^1.0.4
  lottie: ^1.2.1
  focus_detector: ^2.0.0
  camera: ^0.9.4+5
  flip_card: ^0.6.0
  image_cropper: ^1.4.1
  steel_crypt: ^3.0.0+1
  flutter_3des: ^0.0.4
  grouped_list: ^4.1.0
  backdrop: ^0.6.2
  convex_bottom_bar: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  sliding_up_panel: ^2.0.0+1
  share_plus: any
  auto_size_text: ^3.0.0
  geolocator: 7.7.0
  package_info: ^2.0.2
  infobip_mobilemessaging: ^0.5.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  draggable_widget: ^2.0.0
  syncfusion_flutter_sliders: ^19.4.43
#  firebase_messaging: ^11.2.5
  firebase_core: ^1.11.0
  firebase_crashlytics: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/drawable/
    - assets/animation/
    - assets/flags/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/font/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Montserrat-Light.ttf
          weight: 300
        - asset: assets/font/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/font/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/font/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/font/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/font/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Montserrat-Black.ttf
          weight: 900
        - asset: assets/font/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/font/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/font/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/font/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/font/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/font/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
