name: neo_bank
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+2306091


environment:
  sdk: ">=2.15.0 <=3.0.0"

flutter_intl:
  enabled: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  domain:
    path: domain
  data:
    path: data

  card_swiper:
    git:
      url: https://github.com/TheAnkurPanchani/card_swiper.git
      ref: master

  flutter_riverpod: ^2.3.6
  dartz: ^0.10.1
  rxdart: ^0.27.7
  fluttertoast: ^8.2.1
  responsive_builder: ^0.6.4
  animated_theme_switcher: ^2.0.8
  intl: any
  flutter_svg_provider: ^1.0.3
  dots_indicator: ^3.0.0
  carousel_slider: ^4.2.1
  animated_widgets: ^1.1.0
  pin_code_fields: ^7.4.0
  flutter_countdown_timer: ^4.1.0
  flutter_switch: ^0.3.2
  show_up_animation: ^2.0.0
  top_snackbar_flutter: ^3.0.0+1
  fading_edge_scrollview: ^3.0.0
  clickable_list_wheel_view: ^0.2.0
  lottie: ^2.3.2
  focus_detector: ^2.0.1
  camera: ^0.10.5
  flip_card: ^0.7.0
  image_cropper: ^3.0.3
  grouped_list: ^5.1.2
  convex_bottom_bar: ^3.2.0
  smooth_page_indicator: ^1.1.0
  share_plus: any
  auto_size_text: ^3.0.0
  agora_rtc_engine: ^6.1.1
  firebase_analytics: ^10.4.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  syncfusion_flutter_sliders: ^21.2.4
  url_launcher: ^6.1.11
  sms_autofill: ^2.3.0
  firebase_core: ^2.12.0
  firebase_crashlytics: ^3.3.0
  firebase_performance: ^0.9.2
  wakelock: ^0.6.2
  mask_text_input_formatter: ^2.4.0
  device_preview: any
  auto_size_text_field: ^2.2.1
  flutter_slidable: ^3.0.0
  qr_code_scanner: ^1.0.1
  package_info_plus: any
  qr_flutter: ^4.1.0
  syncfusion_flutter_pdfviewer: any


dependency_overrides:
  flutter_inappwebview: ^5.7.2+3


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/drawable/
    - assets/animation/
    - assets/flags/
    - assets/images/
    - assets/images/bill_payments_categories/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/font/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Montserrat-Light.ttf
          weight: 300
        - asset: assets/font/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/font/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/font/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/font/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/font/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Montserrat-Black.ttf
          weight: 900
        - asset: assets/font/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/font/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/font/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/font/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/font/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/font/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Tajawal
      fonts:
        - asset: assets/font/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Tajawal-Light.ttf
          weight: 300
        - asset: assets/font/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/font/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/font/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/font/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Tajawal-Black.ttf
          weight: 900
