source 'https://cdn.cocoapods.org/'
source 'https://github.com/idwise/ios-sdk'

# Uncomment this line to define a global platform for your project
 platform :ios, '13.5'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'InfobipRTC','2.2.1'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  pod 'IDWise', '4.3.4'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
            '$(inherited)',

            ## dart: PermissionGroup.camera
            'PERMISSION_CAMERA=1',

            ## dart: PermissionGroup.microphone
            'PERMISSION_MICROPHONE=1',

          ]
          
          if target.name  == "infobipplugin"
                all_filerefs = installer.pods_project.files
                all_filerefs.each do |fileref|
                   if fileref.path.end_with? "WebRTC.xcframework"
                    build_phase = target.frameworks_build_phase
                    unless build_phase.files_references.include?(fileref)
                      build_phase.add_file_reference(fileref)
                    end
                   end
                end
              end
          
          if target.name  == "infobipplugin"
                all_filerefs = installer.pods_project.files
                all_filerefs.each do |fileref|
                   if fileref.path.end_with? "InfobipRTC.xcframework"
                    build_phase = target.frameworks_build_phase
                    unless build_phase.files_references.include?(fileref)
                      build_phase.add_file_reference(fileref)
                    end
                   end
                end
              end
          
        if config.build_settings['WRAPPER_EXTENSION'] == 'bundle'
           config.build_settings['DEVELOPMENT_TEAM'] = '235F45XS77'

         end
         end
  end
end
