import 'dart:ui';

import 'package:flutter/material.dart';

class AppColor {
  AppColor._();

  static const white1 = const Color(0xffFAFAFA);
  static const very_light_gray_6 = const Color(0xffDFDFDF);
  static const very_light_grey = const Color(0xffF3F3F3);
  static const gray4 = const Color(0xff707070);
  static const dark_blue = const Color(0xff3516A4);
  static const darkGrey = const Color(0xff76777B);
  static const blurr = const Color(0xff272331);
  static const dark_blue1 = const Color(0xff06002C);
  static const very_light_violet = const Color(0xffD3C7F3);
  static const green = const Color(0xffAC9C0D);
  static const lightRed = const Color(0xffFF8391);
  static const veryLightRed = const Color(0xffF9B6BE);
  static const dark_violet = const Color(0xff4417AE);
  static const dark_violet1 = const Color(0xff442399);
  static const dark_violet2 = const Color(0xff412098);
  static const strong_violet = const Color(0xff572BCC);
  static const very_soft_violet = const Color(0xffB699EE);
  static const soft_violet = const Color(0xff7A55DB);
  static const dark_moderate_blue = const Color(0xff5438AE);
  static const dark_gray = const Color(0xff959595);
  static const light_violet = const Color(0xff8269C2);
  static const very_dark_gray = const Color(0xff333333);
  static const vivid_orange = const Color(0xffFFA125);
  static const vivid_red = const Color(0xffFF5630);
  static const very_light_gray = const Color(0xffFAFAFA);
  static const very_dark_blue = const Color(0xff060030);
  static const light_grayish_violet = const Color(0xffF8F6FD);
  static const very_pale_blue = const Color(0xfff2f8ff);
  static const dark_moderate_magenta = const Color(0xffaa42b1);
  static const very_light_gray1 = const Color(0xfff2f2f2);
  static const very_light_gray5 = const Color(0xffC4C4C4);
  static const light_grayish_violet1 = const Color(0xffe5dced);
  static const dark_grayish_violet = const Color(0xff7c7394);
  static const very_light_gray_white = const Color(0xfff8f8f8);
  static const very_pale_blue_white = const Color(0xfff3f2ff);
  static const whiteGray = const Color(0xffF4F4F4);
  static const dark_violet_1 = const Color(0xff4b25af);
  static const dark_violet_2 = const Color(0xff481EAF);
  static const dark_violet_3 = const Color(0xff4a22b0);
  static const dark_violet_4 = const Color(0xff412098);
  static const dark_gray_1 = const Color(0xff8b8b8b);
  static const very_light_violet1 = const Color(0xffa389e6);
  static const very_dark_violet = const Color(0xff272331);
  static const mostly_desaturated_dark_violet = const Color(0xff8270af);
  static const dark_grayish_violet1 = const Color(0xff9C93B2);
  static const gray_1 = const Color(0xffBDBDBD);
  static const text_color = const Color(0xffF8F8F8);
  static const border_color = const Color(0xff8270AF);
  static const gray = const Color(0xff8B8B8B);
  static const light_gray1 = const Color(0xfff2f2f2);
  static const gray_black = const Color(0xff101010);
  static const light_blue = const Color(0xff572BCC);
  static const light_blue1 = const Color(0xff4639FF);
  static const soft_red = const Color(0xffED7863);
  static const very_light_gray_1 = const Color(0xffececec);
  static const very_dark_gray_black1 = const Color(0xff2d2d2d);
  static const grayish_violet = const Color(0xffcdc9d8);
  static const very_dark_gray1 = const Color(0xff5e5e5e);
  static const very_soft_violet_1 = const Color(0xffd5c7fb);
  static const very_soft_blue = const Color(0xff8283e7);
  static const strong_magenta = const Color(0xffB422D1);
  static const strong_violet_1 = const Color(0xff7c1dcf);
  static const light_grayish_violet_1 = const Color(0xffe9dcfe);
  static const dark_grayish_blue = const Color(0xff9A99A2);
  static const pure_blue = const Color(0xff007AFF);
  static const very_dark_blue1 = const Color(0xff29136F);
  static const white_gray = const Color(0xffDDDDDD);

  /// --------- NEW COLOR SCHEME
  static const white = const Color(0xffffffff);
  static const black = const Color(0xff000000);
  static const brightRed = const Color(0xffE53E51);
  static const verySoftRed = const Color(0xffF68D98);
  static const vividYellow = const Color(0xffFFE816);
  static const brightBlue = const Color(0xff3CB4E5);
  static const veryLightGray = const Color(0xffFBFBFB);
  static const lightGray = const Color(0xffF5F5F5);
  static const verLightGray4 = const Color(0xffBCBCBC);
  static const veryLightGray1 = const Color(0xffE8E8E8);
  static const veryLightGray2 = const Color(0xffEEEEEE);
  static const veryDarkGray = const Color(0xff292929);
  static const veryDarkGray1 = const Color(0xff404040);
  static const veryDarkGray2 = const Color(0xff101010);
  static const veryDarkRed = const Color(0xff1A0306);
  static const whiteGrey = const Color(0xffDDDDDD);
  static const gray1 = const Color(0xffB5B5B5);
  static const strongRed = const Color(0xffD82A3E);
  static const very_dark_gray_black = const Color(0xff101010);
  static const lightGrayishMagenta = const Color(0xffECE8EC);
  static const gray_2 = const Color(0xffB5B5B5);
  static const darkGray = const Color(0xff979797);
  static const vividRed = const Color(0xffFF3E33);
  static const darkModerateLimeGreen = const Color(0xff388835);
}
